export const ActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  SET_CURRENCY: "SET_CURRENCY",
  ADJUST_QTY: "ADJUST_QTY",
  LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
